// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_device_thermostat_48dp_ffffff_fill1_wght400_grad0_opsz48_png);    // assets/device_thermostat_48dp_FFFFFF_FILL1_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_electric_meter_48dp_ffffff_fill1_wght400_grad0_opsz48_png);    // assets/electric_meter_48dp_FFFFFF_FILL1_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_humidity_percentage_48dp_ffffff_fill1_wght400_grad0_opsz48_png);    // assets/humidity_percentage_48dp_FFFFFF_FILL1_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_mode_fan_54dp_ffffff_fill1_wght400_grad0_opsz48_png);    // assets/mode_fan_54dp_FFFFFF_FILL1_wght400_GRAD0_opsz48.png

// FONTS
LV_FONT_DECLARE(ui_font_yekanbold24);
LV_FONT_DECLARE(ui_font_yekanreg22);

// UI INIT
void ui_init(lv_disp_t *disp);

void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
