#include "ui_manager.h"
#include "esp_log.h"
#include "esp_timer.h"
#include "esp_lcd_panel_io.h"
#include "esp_lcd_panel_vendor.h"
#include "esp_lcd_panel_ops.h"
#include "driver/gpio.h"
#include "lvgl.h"
#include "sdkconfig.h"
#include <sys/lock.h>

// --- Includes for your UI, generated by SquareLine Studio ---
// #include "ui.h" // <-- You will uncomment this later

static const char *TAG = "UI_Manager";

// --- LVGL Porting ---
static _lock_t lvgl_api_lock;
static esp_lcd_panel_handle_t panel_handle = NULL;
#define LVGL_TICK_PERIOD_MS 2
#define LVGL_TASK_MAX_DELAY_MS 500
#define LVGL_TASK_MIN_DELAY_MS 1
#define LVGL_TASK_STACK_SIZE (4 * 1024)
#define LVGL_TASK_PRIORITY 2

static bool notify_lvgl_flush_ready(esp_lcd_panel_io_handle_t panel_io, esp_lcd_panel_io_event_data_t *edata, void *user_ctx)
{
    lv_display_t *display = (lv_display_t *)user_ctx;
    lv_display_flush_ready(display);
    return false;
}

static void lvgl_flush_cb(lv_display_t *display, const lv_area_t *area, uint8_t *color_map)
{
    esp_lcd_panel_handle_t panel_handle = lv_display_get_user_data(display);
    int offsetx1 = area->x1;
    int offsetx2 = area->x2;
    int offsety1 = area->y1;
    int offsety2 = area->y2;
    esp_lcd_panel_draw_bitmap(panel_handle, offsetx1, offsety1, offsetx2 + 1, offsety2 + 1, color_map);
}

static void increase_lvgl_tick(void *arg)
{
    lv_tick_inc(LVGL_TICK_PERIOD_MS);
}

static void lvgl_port_task(void *arg)
{
    ESP_LOGI(TAG, "Starting LVGL task");
    uint32_t time_till_next_ms = 0;
    while (1)
    {
        _lock_acquire(&lvgl_api_lock);
        time_till_next_ms = lv_timer_handler();
        _lock_release(&lvgl_api_lock);
        vTaskDelay(pdMS_TO_TICKS(time_till_next_ms));
    }
}


void ui_manager_start(void)
{
    ESP_LOGI(TAG, "Initializing Display and LVGL...");

    // --- 1. Initialize Display Hardware ---
    esp_lcd_i80_bus_handle_t i80_bus = NULL;
    esp_lcd_i80_bus_config_t bus_config = {
        .dc_gpio_num = CONFIG_LCD_PIN_DC,
        .wr_gpio_num = CONFIG_LCD_PIN_WR,
        .data_gpio_nums = {
            CONFIG_LCD_PIN_DATA0,
            CONFIG_LCD_PIN_DATA1,
            CONFIG_LCD_PIN_DATA2,
            CONFIG_LCD_PIN_DATA3,
            CONFIG_LCD_PIN_DATA4,
            CONFIG_LCD_PIN_DATA5,
            CONFIG_LCD_PIN_DATA6,
            CONFIG_LCD_PIN_DATA7,
        },
        .bus_width = 8,
        .max_transfer_bytes = CONFIG_LCD_H_RES * 100 * sizeof(uint16_t),
    };
    ESP_ERROR_CHECK(esp_lcd_new_i80_bus(&bus_config, &i80_bus));

    esp_lcd_panel_io_handle_t io_handle = NULL;
    esp_lcd_panel_io_i80_config_t io_config = {
        .cs_gpio_num = CONFIG_LCD_PIN_CS,
        .pclk_hz = CONFIG_LCD_PIXEL_CLOCK_HZ,
        .trans_queue_depth = 10,
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_io_i80(i80_bus, &io_config, &io_handle));

    esp_lcd_panel_dev_config_t panel_config = {
        .reset_gpio_num = CONFIG_LCD_PIN_RST,
        .rgb_endian = LCD_RGB_ENDIAN_RGB,
        .bits_per_pixel = 16,
    };
    ESP_ERROR_CHECK(esp_lcd_new_panel_st7789(io_handle, &panel_config, &panel_handle));
    esp_lcd_panel_reset(panel_handle);
    esp_lcd_panel_init(panel_handle);
    esp_lcd_panel_disp_on_off(panel_handle, true);

    // --- 2. Initialize LVGL ---
    lv_init();
    lv_display_t *display = lv_display_create(CONFIG_LCD_H_RES, CONFIG_LCD_V_RES);
    size_t draw_buffer_sz = CONFIG_LCD_H_RES * 50 * sizeof(uint16_t);
    void *buf1 = malloc(draw_buffer_sz);
    void *buf2 = malloc(draw_buffer_sz);
    lv_display_set_buffers(display, buf1, buf2, draw_buffer_sz, LV_DISPLAY_RENDER_MODE_PARTIAL);
    lv_display_set_user_data(display, panel_handle);
    lv_display_set_flush_cb(display, lvgl_flush_cb);
    const esp_lcd_panel_io_callbacks_t cbs = {.on_color_trans_done = notify_lvgl_flush_ready};
    esp_lcd_panel_io_register_event_callbacks(io_handle, &cbs, display);

    // // --- 3. Initialize LVGL Input Device (Keypad) ---
    // lv_indev_t *indev = lv_indev_create();
    // lv_indev_set_type(indev, LV_INDEV_TYPE_KEYPAD);

    // --- 4. Start LVGL Timers and Tasks ---
    const esp_timer_create_args_t lvgl_tick_timer_args = {.callback = &increase_lvgl_tick, .name = "lvgl_tick"};
    esp_timer_handle_t lvgl_tick_timer = NULL;
    ESP_ERROR_CHECK(esp_timer_create(&lvgl_tick_timer_args, &lvgl_tick_timer));
    ESP_ERROR_CHECK(esp_timer_start_periodic(lvgl_tick_timer, LVGL_TICK_PERIOD_MS * 1000));
    xTaskCreate(lvgl_port_task, "LVGL_Task", LVGL_TASK_STACK_SIZE, NULL, LVGL_TASK_PRIORITY, NULL);

    // --- 5. Load the UI ---
    _lock_acquire(&lvgl_api_lock);
    // Here you will call the UI function generated by SquareLine Studio
    // For example:
    // ui_init();
    _lock_release(&lvgl_api_lock);
}