// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef SPLASH_SCREEN_H
#define SPLASH_SCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

    // SCREEN: ui_Screen1
    extern void splash_screen_init(void);
    extern void splash_screen_destroy(void);
    extern lv_obj_t *splash_Screen;
    // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
