// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

// #include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "views/dashboard_view.h"
#include "screens/splash_screen.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
// (no bitmap assets required for the current thermostat screen)

// FONTS
LV_FONT_DECLARE(font_geist_14);
LV_FONT_DECLARE(font_geist_24);
LV_FONT_DECLARE(font_yekan_bakh_16);

// UI INIT
void ui_init(lv_disp_t *disp);

void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
