// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"
#include "lv_lottie.h"

#define LOTTIE_WIDTH 80
#define LOTTIE_HEIGHT 80

extern const uint8_t ai_logo_data[];
extern const size_t ai_logo_data_size;

lv_obj_t *splash_Screen = NULL;
lv_obj_t *lottie = NULL;
// event funtions

// build funtions

void splash_screen_init(void)
{
    splash_Screen = lv_obj_create(NULL);
    lv_obj_remove_flag(splash_Screen, LV_OBJ_FLAG_SCROLLABLE);

    // lottie = lv_lottie_create(lv_screen_active());
    // Create the Lottie widget
    lottie = lv_lottie_create(splash_Screen);
    lv_lottie_set_src_data(lottie, ai_logo_data, ai_logo_data_size);

    // Create a static buffer to hold the rendered frames
    // The size is width * height * 4 bytes (for ARGB8888)
    static uint8_t lottie_buffer[LOTTIE_WIDTH * LOTTIE_HEIGHT * 4];
    lv_lottie_set_buffer(lottie, LOTTIE_WIDTH, LOTTIE_HEIGHT, lottie_buffer);
    lv_obj_center(lottie);
}

void splash_screen_destroy(void)
{
    if (splash_Screen)
        lv_obj_del(splash_Screen);

    // NULL screen variables
    splash_Screen = NULL;
    lottie = NULL;
}
