// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_TempIcon = NULL;
lv_obj_t * ui_OnLabel = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_CurrentIcon = NULL;
lv_obj_t * ui_CurrentLabel = NULL;
lv_obj_t * ui_HummidityIcon = NULL;
lv_obj_t * ui_HummidityLabel = NULL;
lv_obj_t * ui_FanIcon = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TempIcon = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_TempIcon, &ui_img_device_thermostat_48dp_ffffff_fill1_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_TempIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_TempIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_TempIcon, -81);
    lv_obj_set_y(ui_TempIcon, 64);
    lv_obj_set_align(ui_TempIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_TempIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_TempIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OnLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_OnLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OnLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OnLabel, -80);
    lv_obj_set_y(ui_OnLabel, -32);
    lv_obj_set_align(ui_OnLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OnLabel, "روشن");
    lv_obj_set_style_text_color(ui_OnLabel, lv_color_hex(0x09FD8F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OnLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OnLabel, &ui_font_yekanbold24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 92);
    lv_obj_set_y(ui_TempLabel, -30);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "24.5 °C");
    lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempLabel, &ui_font_yekanreg22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CurrentIcon = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_CurrentIcon, &ui_img_electric_meter_48dp_ffffff_fill1_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_CurrentIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_CurrentIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_CurrentIcon, -131);
    lv_obj_set_y(ui_CurrentIcon, 133);
    lv_obj_set_align(ui_CurrentIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_CurrentIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_CurrentIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_CurrentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentLabel, -75);
    lv_obj_set_y(ui_CurrentLabel, 35);
    lv_obj_set_align(ui_CurrentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CurrentLabel, "110 mA");
    lv_obj_set_style_text_color(ui_CurrentLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CurrentLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CurrentLabel, &ui_font_yekanreg22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HummidityIcon = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_HummidityIcon, &ui_img_humidity_percentage_48dp_ffffff_fill1_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_HummidityIcon, LV_SIZE_CONTENT);   /// 48
    lv_obj_set_height(ui_HummidityIcon, LV_SIZE_CONTENT);    /// 48
    lv_obj_set_x(ui_HummidityIcon, -81);
    lv_obj_set_y(ui_HummidityIcon, 133);
    lv_obj_set_align(ui_HummidityIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_HummidityIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HummidityIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HummidityLabel = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_HummidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HummidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HummidityLabel, 86);
    lv_obj_set_y(ui_HummidityLabel, 40);
    lv_obj_set_align(ui_HummidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HummidityLabel, "98 %");
    lv_obj_set_style_text_color(ui_HummidityLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HummidityLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HummidityLabel, &ui_font_yekanreg22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanIcon = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_FanIcon, &ui_img_mode_fan_54dp_ffffff_fill1_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_FanIcon, LV_SIZE_CONTENT);   /// 54
    lv_obj_set_height(ui_FanIcon, LV_SIZE_CONTENT);    /// 54
    lv_obj_set_x(ui_FanIcon, -131);
    lv_obj_set_y(ui_FanIcon, 64);
    lv_obj_set_align(ui_FanIcon, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_FanIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_FanIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_TempIcon = NULL;
    ui_OnLabel = NULL;
    ui_TempLabel = NULL;
    ui_CurrentIcon = NULL;
    ui_CurrentLabel = NULL;
    ui_HummidityIcon = NULL;
    ui_HummidityLabel = NULL;
    ui_FanIcon = NULL;

}
