// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_TempIcon;
extern lv_obj_t * ui_OnLabel;
extern lv_obj_t * ui_TempLabel;
extern lv_obj_t * ui_CurrentIcon;
extern lv_obj_t * ui_CurrentLabel;
extern lv_obj_t * ui_HummidityIcon;
extern lv_obj_t * ui_HummidityLabel;
extern lv_obj_t * ui_FanIcon;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

